### PR TITLE
#453 Added docker-compose from other repos

### PR DESCRIPTION
**Pull request by jenow**

### CODE REVIEW

**Comment by dbengsch** [comment]
Did we discuss about the utility of this repository ?

**Comment by benoitvidis** [comment]
I agree with @dbengsch . Why do we need to move them?
It makes more sense to me to keep them in their dedicated repositories.

**Comment by benoitvidis** [comment]
Ok, now I remember why we wanted to do this and I agree.

@dbengsch What I remember:
To run a production stack using Kuzzle' resources, one has 2 choices:

1. get the docker-compose.yml from the doc (from raw.github.com)
2. clone the whole repository

Option 1 does not matter where the docker-compose.yml is.
The second one is more a problem as the code does not help much in deployment. Centralizing the deployment recipes make it a little more useful (can notably be used in Kuzzle own deployment recipes).

**Comment by jenow** [comment]
Yes that was the reason. We could potentially keep the docker-compose.yml in each repository though

**Comment by ballinette** [comment]
So, wy not keepying docker-compose.yml in each repo and tell people to download https://raw.githubusercontent.com/kuzzleio/kuzzle/master/docker-compose.yml ?

**Pull request merged**
