### PR TITLE
154 systemd

### PR DESCRIPTION
**Pull request by jenow**
Add scripts to add or remove kuzzle on boot
Documentation: https://github.com/kuzzleio/documentation/pull/461

Depends on #30
Fix kuzzleio/kuzzle-backlog#154

### CODE REVIEW

**Comment by Aschen** [comment]
Maybe you can inform the user about the systemd scripts `add-kuzzle-boot-systemd.sh` and `remove-kuzzle-boot-systemd.sh` ?

**Comment by benoitvidis** [comment]
TL;DR for the time being. Waiting for #30 to be merged for reviewing.

@Aschen: we agreed the setup.sh itself output should be kept minimal & clear to avoir confusion. 
+1 to ship a README with additional infos though

**Comment by jenow** [comment]
@Aschen the user does not clone this repository to get the setup.sh, but I wrote documentation on kuzzleio about it

**Comment by benoitvidis** [comment]
@ballinette cf my previous answer to @Aschen

**Comment by ballinette** [comment]
@benoitvidis So why do we write  `you can see the logs...` again ?

**Comment by ballinette** [comment]
anyway, it's not blocking... could be added in former enhancements...

**Pull request merged**
